### ISSUE TITLE
Slice out of bounds error when applying MatchString

### ISSUE THREAD

**Issue by provector** [Jemmic/go-pcre2#1]
Hi,

Running this Regex (on linux, checked wih go versions 1.11 and 1.17)

`<(\d{1,3})>[\d{1,}: \*]*((?:[JFMASONDjfmasond]\w\w) {1,2}(?:\d+)(?: \d{4})? (?:\d{2}:\d{2}:\d{2}[\.\d{1,3}]*)(?: [A-Z]{1,3}:)?)?:?\s*(?:((?:[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})|(?:[a-zA-Z0-9\-]+)|(?:(?:(?:[0-9A-Fa-f]{1,4}:){7}(?:[0-9A-Fa-f]{1,4}|:))|(?:(?:[0-9A-Fa-f]{1,4}:){6}(?::[0-9A-Fa-f]{1,4}|(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(?:(?:[0-9A-Fa-f]{1,4}:){5}(?:(?:(?::[0-9A-Fa-f]{1,4}){1,2})|:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(?:(?:[0-9A-Fa-f]{1,4}:){4}(?:(?:(?::[0-9A-Fa-f]{1,4}){1,3})|(?:(?::[0-9A-Fa-f]{1,4})?:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(?:(?:[0-9A-Fa-f]{1,4}:){3}(?:(?:(?::[0-9A-Fa-f]{1,4}){1,4})|(?:(?::[0-9A-Fa-f]{1,4}){0,2}:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(?:(?:[0-9A-Fa-f]{1,4}:){2}(?:(?:(?::[0-9A-Fa-f]{1,4}){1,5})|(?:(?::[0-9A-Fa-f]{1,4}){0,3}:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(?:(?:[0-9A-Fa-f]{1,4}:){1}(?:(?:(?::[0-9A-Fa-f]{1,4}){1,6})|(?:(?::[0-9A-Fa-f]{1,4}){0,4}:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(?::(?:(?:(?::[0-9A-Fa-f]{1,4}){1,7})|(?:(?::[0-9A-Fa-f]{1,4}){0,5}:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(?:%.+)?) )?(.*)`

against that line: 

`<189>91: *Oct 16 2010 21:48:41.663 UTC: %SYS-5-CONFIG_I: Configured from console by cisco on vty0 (192.168.200.1)`

yields the following error:

`
panic: runtime error: slice bounds out of range [:18446744073709551615] with length 109

goroutine 1 [running]:
github.com/Jemmic/go-pcre2.(*Matcher).Group(0xc0000740a0, 0xc000010018)
        /home/provector/GOPATTH/pkg/mod/github.com/!jemmic/go-pcre2@v0.0.0-20190111114109-bd52ad5f7098/pcre.go:913 +0x20d
main.processMessage({0x4a52ca, 0x6d})
        /home/provector/IdeaProjects/debugPcre/main.go:59 +0x22b
main.main()
        /home/provector/IdeaProjects/debugPcre/main.go:39 +0x189

Process finished with the exit code 2
`

After doing some investigation and debugging, it looks like the third (out of 4) capture group pointers are completely wrong:

`Vector array entry at index 0 is [0]`
`Vector array entry at index 1 is [109]`
`Vector array entry at index 2 is [1]`
`Vector array entry at index 3 is [4]`
`Vector array entry at index 4 is [10]`
`Vector array entry at index 5 is [35]`
`Vector array entry at index 6 is [18446744073709551615]`
`Vector array entry at index 7 is [18446744073709551615]`
`Vector array entry at index 8 is [36]`
`Vector array entry at index 9 is [109]`

These are adjusted in mData.ovector table during call to C.pcre2_match, I haven't had time to investigate it any further.

Reason I believe it might be a bug is that exactly same regex with the provided test line works fine in: native Perl, native Java, native Go regexp library and other implementation of pcre2 wrapper for go (lesttrat one, but unfortunately this one is twice slower than Your library). Any help or pointers towards debugging would be greatly appreciated :) 

Also, could it be just a case of getting the flags right? I was searching the internet for any docs on pcre2 flags and how to convert them to uint32 but I'm completely lost there :(

P.S. Also apologies for the messy markdown

**Comment by rrthomas** [comment]
The indices for the 3rd group are correct: it's a non-match, which uses 64-bit -1.

The problem is that go-pcre2 doesn't check for these non-matches in many places where it should.

I have fixed this on my fork at rrthomas/go-pcre2.
