### ISSUE TITLE
panic: Matcher.Init: uninitialized

### ISSUE THREAD

**Issue by sunshine69** [Jemmic/go-pcre2#2]
Hi Team,

I got a function like this (trying to mimic the go regexp version). The intention is that I can pre-compile the pattern or pass it as string.

However it works when I pass it as string, not if I compile - it always throw errors

```
panic: Matcher.Init: uninitialized

goroutine 1 [running]:
github.com/Jemmic/go-pcre2.(*Matcher).Init(0x0?, 0x841cc6?)
        /home/sitsxk5/go/pkg/mod/github.com/!jemmic/go-pcre2@v0.0.0-20190111114109-bd52ad5f7098/pcre.go:740 +0xc5
github.com/Jemmic/go-pcre2.(*Regexp).NewMatcher(...)
        /home/sitsxk5/go/pkg/mod/github.com/!jemmic/go-pcre2@v0.0.0-20190111114109-bd52ad5f7098/pcre.go:703
setupprojectansible/lib.Pcre2FindAllStringSubmatchV2[...](0xc000056060?, {0x841cc6?, 0x1c?})
        /home/sitsxk5/src/setup-project-ansible-go/lib/pcre2.go:119 +0x2c9
main.main()
        /home/sitsxk5/src/setup-project-ansible-go/plays/test-pcre2/main.go:74 +0x37e
exit status 2
```

The function is below. PLease help if anything I do is wrong? Thanks in advance

```
// go-pcre2 implementation of FindAllStringSubmatch
func Pcre2FindAllStringSubmatchV2[T string | *pcre2.Regexp](pattern T, input string) ([][]string, error) {
	var re *pcre2.Regexp
	anyPattern := any(pattern)
	if _ptn, ok := anyPattern.(*pcre2.Regexp); ok {
		re = _ptn
	} else {
		var err error
		if _ptn, ok := anyPattern.(string); ok {
			re, err = pcre2.Compile(_ptn, 0)
			if err != nil {
				return nil, fmt.Errorf("failed to compile pattern: %w", err)
			}
			defer re.Free()
		} else {
			return nil, fmt.Errorf("failed to assert pattern is string %v", pattern)
		}
	}

	var allMatches [][]string
	offset := 0
	inputBytes := []byte(input)

	for {
		// Match the string from the current offset
		re.NewMatcher().Init(re)
		m := re.Matcher(inputBytes[offset:], 0)
		if !m.Matches() {
			break
		}

		// Extract matched groups
		var groups []string
		// Always append the full match (group 0) first
		groups = append(groups, m.GroupString(0))

		// Extract other capturing groups
		for i := 1; i <= m.Groups(); i++ {
			group := m.GroupString(i)
			groups = append(groups, group)
		}

		// Use the first group (full match) to update the offset correctly
		groupIndices := m.GroupIndices(0) // Get indices for the full match (group 0)
		offset += groupIndices[1]         // Shift offset to the end of the match

		// Store the match result
		allMatches = append(allMatches, groups)

		// Stop if we've processed the entire string
		if offset >= len(inputBytes) {
			break
		}
	}

	return allMatches, nil
}
```

**Comment by sunshine69** [comment]
It might be due to the way CGO and I use in goroutine. If I move the ptn compiled closer to the scope I call the func above then it works fine.

I think go by default always pass by value even pointer - it should not happen nevertheless. Anyway I have it working so it might be non-issue.
Thanks
